services:
  mongo-jenkins:
    image: mongo:6.0
    container_name: mongo-jenkins
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_jenkins:/data/db
    restart: unless-stopped
    
  backend-jenkins:
    image: node:18
    container_name: backend-jenkins
    working_dir: /app
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm start"
    environment:
      - DATABASE=mongodb://mongo-jenkins:27017/ecommerce
      - PORT=5000
    depends_on:
      - mongo-jenkins
    restart: unless-stopped
    
  frontend-jenkins:
    image: node:16
    container_name: frontend-jenkins
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
    command: sh -c "npm install --legacy-peer-deps && HOST=0.0.0.0 npm start"
    environment:
      - REACT_APP_API_URL=http://51.20.104.42:5001
    depends_on:
      - backend-jenkins
    restart: unless-stopped

volumes:
  mongo_data_jenkins:
